services:
  - type: web
    name: jphn-transfer
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 180 --workers 1 --worker-class=sync --max-requests 100 --max-requests-jitter 10
    healthCheckPath: /health
    envVars:
      - key: FLASK_CONFIG
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: jphn-db
          property: connectionString
      - key: PYTHONUNBUFFERED
        value: "1"

databases:
  - name: jphn-db
    plan: free
